- name: "envoy-admin"
  dns_refresh_rate: "24h"
  routes:
    - match_type: "path"
      path_prefix: "/envoy-admin"
      prefix_rewrite: "/"
  instances:
    - host: "127.0.0.1"
      port: 19000
- name: "rest-service-tls"
  dns_refresh_rate: "5m"
  tls: true
  routes:
    - match_type: "path"
      path_prefix: "/rest-service-tls/"
      prefix_rewrite: "/"
  instances:
    - host: "rest-service-tls-1"
      port: 8443
    - host: "rest-service-tls-2"
      port: 8443
- name: "grpc-service"
  dns_refresh_rate: "5m"
  http2: true
  routes:
    - match_type: "header"
      header_name: "X-Service"
      header_value: "grpc-service"
  instances:
    - host: "grpc-service-1"
      port: 9090
