- name: "envoy-admin"
  instances:
    - host: "127.0.0.1"
      port: 19000
  routes:
    - match_type: "path"
      path_prefix: "/envoy-admin"
      prefix_rewrite: "/"
- name: "envoy-io"
  instances:
    - host: "envoyproxy.io"
      port: 443
  tls: true
  routes:
    - match_type: "path"
      path_prefix: "/docs"
      prefix_rewrite: "/docs"